apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: test-multiple-kinds
spec:
  namespace: test-multiple-kinds
  git:
    folder: service-test-multiple-kinds
    ref: main
  repositoryRef:
    kind: GitRepository
    name: plural-manifests
  clusterRef:
    kind: Cluster
    name: target-cluster
    namespace: default
