apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: test-wordpress
spec:
  namespace: test-wordpress
  helm:
    url: https://charts.bitnami.com
    version: 26.0.0
    values:
      image:
        debug: true
    chart: wordpress
  clusterRef:
    kind: Cluster
    name: target-cluster
    namespace: default