apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: test-argo-cd
spec:
  namespace: test-argo-cd
  helm:
    url: oci://ghcr.io/argoproj/argo-helm
    version: 9.1.3
    chart: argo-cd
    values:
      redisSecretInit:
        jobAnnotations:
          deployment.plural.sh/sync-hook-delete-policy: hook-succeeded
          deployment.plural.sh/sync-options: Force=True
  clusterRef:
    kind: Cluster
    name: target-cluster
    namespace: default
